# Site settings
title:  Welcome to my abode
subtitle: on the world wide web
email: khizaranjum28 AT gmail 
description: A place where I share myself with the world
baseurl: "/" # the subpath of your site, e.g. /blog
#url: "http://10.42.0.1:4000" # development url
url: "https://khizar-anjum.github.io" # the base hostname & protocol for your site
host: "10.42.0.1" #development
author: Khizar
street_address: Greater New York City Area
#city: Nashville
#state: TN
#zip_code: 55555
country: United States of America
#phone: (716) 555-5555

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/khizar-anjum
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/khizaranjum28
linkedin_url: https://www.linkedin.com/in/khizar-anjum
pinterest_url:
slack_url: 
twitter_url: https://twitter.com/theselfishjeans
kaggle_url: https://www.kaggle.com/khizaranjum

google_analytics: UA-156338845-1


# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap

collections:
  rcorner:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  gi:
    output: true
    permalink: /:collection/:path/
